name: JasstafelWeb

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use latest Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build -- --prod
    - name: Test
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: E2E
      run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
